<div class="menu" align="left"> <b><a href="/"><i>SDCC Home</i></a></b>
  <div class="submenu">
    <a href="/index.php#News"><i>News</i></a><br />
    <a href="/index.php#Platforms"><i>Platforms</i></a><br />
    <a href="/index.php#Download"><i>Download</i></a><br />
    <a href="/index.php#Support"><i>Support</i></a><br />
    <a href="/index.php#Who"><i>Who</i></a><br />
  </div>
  <br />
  <b><a href="/snap.php"><i>Snapshots</i></a></b>
  <div class="submenu">
    <a href="/snap.php#Linux"><i>Linux</i></a><br />
    <a href="/snap.php#Windows"><i>Windows</i></a><br />
    <a href="/snap.php#MacOSX"><i>Mac OS X</i></a><br />
    <a href="/snap.php#Docs"><i>Documentation</i></a><br />
    <a href="/snap.php#Source"><i>Source</i></a><br />
  </div>
  <br />
  <b><a href="/regtests.php"><i>Regression Tests</i></a></b>
  <div class="submenu">
    <a href="/regtests.php#Database"><i>Download CSV</i></a><br />
    <a href="/regtests.php#Diffs"><i>Differences</i></a><br />
  </div>
  <br />
  <b><i>Documentation</i></b>
  <div class="submenu">
    <a href="/doc/sdccman.pdf"><i>SDCC Manual (pdf)</i></a><br />
  </div>
  <br />
  <b><a href="http://sourceforge.net/projects/sdcc"><i>SDCC at SourceForge</i></a></b>
  <div class="submenu">
    <a href="http://sourceforge.net/project/showfiles.php?group_id=599"><i>SDCC File Releases</i></a><br />
    <a href="https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/"><i>SDCC Subversion Repository</i></a><br />
    <a href="https://sourceforge.net/p/sdcc/discussion/"><i>SDCC Forum</i></a><br />
  </div>
  <br />
  <b><a href="http://sdcc.sourceforge.net/wiki/"><i>SDCC Wiki</i></a></b><br />
  <br />
  <b><a href="/links.php"><i>Links and More!</i></a></b><br />
  <br />
  <b><a href="http://www.ohloh.net/projects/425"><i>SDCC Metrics by Ohloh</i></a></b><br />
  <script type='text/javascript' language='JavaScript' src='http://www.ohloh.net/projects/425;badge_js'></script><br />
</div>
