include $(TOPDIR)/Makefile.common

OBJ = $(SRC:%.c=%.o)
LIB = $(TOPDIR)/lib/$(THIS).a

all: $(TOPDIR)/lib $(LIB)

$(TOPDIR)/lib:
	mkdir -p $(TOPDIR)/lib

$(LIB): $(OBJ)
	rm -f $(LIB)
	ar r $(LIB) $(OBJ)
	$(RANLIB) $(LIB)

clean:
	rm -f $(OBJ) $(LIB) *~

