/* Register definitions for pic12f752.
 * This file was automatically generated by:
 *   inc2h.pl
 *   Copyright (c) 2002, Kevin L. Pauba, All Rights Reserved
 *
 * SDCC is licensed under the GNU Public license (GPL) v2. Note that
 * this license covers the code to the compiler and other executables,
 * tbut explicitly does not cover any code or objects generated by sdcc.
 *
 *
 * For pic device libraries and header files which are derived from
 * Microchip header (.inc) and linker script (.lkr) files Microchip
 * requires that "The header files should state that they are only to be
 * used with authentic Microchip devices" which makes them incompatible
 * with the GPL. Pic device libraries and header files are located at
 * non-free/lib and non-free/include directories respectively.
 * Sdcc should be run with the --use-non-free command line option in
 * order to include non-free header files and libraries.
 *
 * See http://sdcc.sourceforge.net/ for the latest information on sdcc.
 */
#include <pic12f752.h>

__sfr  __at (INDF_ADDR)                    INDF;
__sfr  __at (TMR0_ADDR)                    TMR0;
__sfr  __at (PCL_ADDR)                     PCL;
__sfr  __at (STATUS_ADDR)                  STATUS;
__sfr  __at (FSR_ADDR)                     FSR;
__sfr  __at (PORTA_ADDR)                   PORTA;
__sfr  __at (IOCAF_ADDR)                   IOCAF;
__sfr  __at (PCLATH_ADDR)                  PCLATH;
__sfr  __at (INTCON_ADDR)                  INTCON;
__sfr  __at (PIR1_ADDR)                    PIR1;
__sfr  __at (PIR2_ADDR)                    PIR2;
__sfr  __at (TMR1_ADDR)                    TMR1;
__sfr  __at (TMR1L_ADDR)                   TMR1L;
__sfr  __at (TMR1H_ADDR)                   TMR1H;
__sfr  __at (T1CON_ADDR)                   T1CON;
__sfr  __at (T1GCON_ADDR)                  T1GCON;
__sfr  __at (CCPR1_ADDR)                   CCPR1;
__sfr  __at (CCPR1L_ADDR)                  CCPR1L;
__sfr  __at (CCPR1H_ADDR)                  CCPR1H;
__sfr  __at (CCP1CON_ADDR)                 CCP1CON;
__sfr  __at (ADRES_ADDR)                   ADRES;
__sfr  __at (ADRESL_ADDR)                  ADRESL;
__sfr  __at (ADRESH_ADDR)                  ADRESH;
__sfr  __at (ADCON0_ADDR)                  ADCON0;
__sfr  __at (ADCON1_ADDR)                  ADCON1;
__sfr  __at (OPTION_REG_ADDR)              OPTION_REG;
__sfr  __at (TRISA_ADDR)                   TRISA;
__sfr  __at (IOCAP_ADDR)                   IOCAP;
__sfr  __at (PIE1_ADDR)                    PIE1;
__sfr  __at (PIE2_ADDR)                    PIE2;
__sfr  __at (OSCCON_ADDR)                  OSCCON;
__sfr  __at (FVRCON_ADDR)                  FVRCON;
__sfr  __at (DACCON0_ADDR)                 DACCON0;
__sfr  __at (DACCON1_ADDR)                 DACCON1;
__sfr  __at (C2CON0_ADDR)                  C2CON0;
__sfr  __at (CM2CON0_ADDR)                 CM2CON0;
__sfr  __at (C2CON1_ADDR)                  C2CON1;
__sfr  __at (CM2CON1_ADDR)                 CM2CON1;
__sfr  __at (C1CON0_ADDR)                  C1CON0;
__sfr  __at (CM1CON0_ADDR)                 CM1CON0;
__sfr  __at (C1CON1_ADDR)                  C1CON1;
__sfr  __at (CM1CON1_ADDR)                 CM1CON1;
__sfr  __at (CMOUT_ADDR)                   CMOUT;
__sfr  __at (MCOUT_ADDR)                   MCOUT;
__sfr  __at (LATA_ADDR)                    LATA;
__sfr  __at (IOCAN_ADDR)                   IOCAN;
__sfr  __at (WPUA_ADDR)                    WPUA;
__sfr  __at (SLRCONA_ADDR)                 SLRCONA;
__sfr  __at (PCON_ADDR)                    PCON;
__sfr  __at (TMR2_ADDR)                    TMR2;
__sfr  __at (PR2_ADDR)                     PR2;
__sfr  __at (T2CON_ADDR)                   T2CON;
__sfr  __at (HLTMR1_ADDR)                  HLTMR1;
__sfr  __at (HLTPR1_ADDR)                  HLTPR1;
__sfr  __at (HLT1CON0_ADDR)                HLT1CON0;
__sfr  __at (HLT1CON1_ADDR)                HLT1CON1;
__sfr  __at (ANSELA_ADDR)                  ANSELA;
__sfr  __at (APFCON_ADDR)                  APFCON;
__sfr  __at (OSCTUNE_ADDR)                 OSCTUNE;
__sfr  __at (PMCON1_ADDR)                  PMCON1;
__sfr  __at (PMCON2_ADDR)                  PMCON2;
__sfr  __at (PMADR_ADDR)                   PMADR;
__sfr  __at (PMADRL_ADDR)                  PMADRL;
__sfr  __at (PMADRH_ADDR)                  PMADRH;
__sfr  __at (PMDAT_ADDR)                   PMDAT;
__sfr  __at (PMDATL_ADDR)                  PMDATL;
__sfr  __at (PMDATH_ADDR)                  PMDATH;
__sfr  __at (COG1PH_ADDR)                  COG1PH;
__sfr  __at (COG1BLK_ADDR)                 COG1BLK;
__sfr  __at (COG1DB_ADDR)                  COG1DB;
__sfr  __at (COG1CON0_ADDR)                COG1CON0;
__sfr  __at (COG1CON1_ADDR)                COG1CON1;
__sfr  __at (COG1ASD_ADDR)                 COG1ASD;

//
// bitfield definitions
//
volatile __ADCON0bits_t __at(ADCON0_ADDR) ADCON0bits;
volatile __ADCON1bits_t __at(ADCON1_ADDR) ADCON1bits;
volatile __ANSELAbits_t __at(ANSELA_ADDR) ANSELAbits;
volatile __APFCONbits_t __at(APFCON_ADDR) APFCONbits;
volatile __C1CON0bits_t __at(C1CON0_ADDR) C1CON0bits;
volatile __C1CON1bits_t __at(C1CON1_ADDR) C1CON1bits;
volatile __C2CON0bits_t __at(C2CON0_ADDR) C2CON0bits;
volatile __C2CON1bits_t __at(C2CON1_ADDR) C2CON1bits;
volatile __CCP1CONbits_t __at(CCP1CON_ADDR) CCP1CONbits;
volatile __CM1CON0bits_t __at(CM1CON0_ADDR) CM1CON0bits;
volatile __CM1CON1bits_t __at(CM1CON1_ADDR) CM1CON1bits;
volatile __CM2CON0bits_t __at(CM2CON0_ADDR) CM2CON0bits;
volatile __CM2CON1bits_t __at(CM2CON1_ADDR) CM2CON1bits;
volatile __CMOUTbits_t __at(CMOUT_ADDR) CMOUTbits;
volatile __COG1ASDbits_t __at(COG1ASD_ADDR) COG1ASDbits;
volatile __COG1BLKbits_t __at(COG1BLK_ADDR) COG1BLKbits;
volatile __COG1CON0bits_t __at(COG1CON0_ADDR) COG1CON0bits;
volatile __COG1CON1bits_t __at(COG1CON1_ADDR) COG1CON1bits;
volatile __COG1DBbits_t __at(COG1DB_ADDR) COG1DBbits;
volatile __COG1PHbits_t __at(COG1PH_ADDR) COG1PHbits;
volatile __DACCON0bits_t __at(DACCON0_ADDR) DACCON0bits;
volatile __DACCON1bits_t __at(DACCON1_ADDR) DACCON1bits;
volatile __FVRCONbits_t __at(FVRCON_ADDR) FVRCONbits;
volatile __HLT1CON0bits_t __at(HLT1CON0_ADDR) HLT1CON0bits;
volatile __HLT1CON1bits_t __at(HLT1CON1_ADDR) HLT1CON1bits;
volatile __INTCONbits_t __at(INTCON_ADDR) INTCONbits;
volatile __IOCAFbits_t __at(IOCAF_ADDR) IOCAFbits;
volatile __IOCANbits_t __at(IOCAN_ADDR) IOCANbits;
volatile __IOCAPbits_t __at(IOCAP_ADDR) IOCAPbits;
volatile __LATAbits_t __at(LATA_ADDR) LATAbits;
volatile __MCOUTbits_t __at(MCOUT_ADDR) MCOUTbits;
volatile __OPTION_REGbits_t __at(OPTION_REG_ADDR) OPTION_REGbits;
volatile __OSCCONbits_t __at(OSCCON_ADDR) OSCCONbits;
volatile __OSCTUNEbits_t __at(OSCTUNE_ADDR) OSCTUNEbits;
volatile __PCONbits_t __at(PCON_ADDR) PCONbits;
volatile __PIE1bits_t __at(PIE1_ADDR) PIE1bits;
volatile __PIE2bits_t __at(PIE2_ADDR) PIE2bits;
volatile __PIR1bits_t __at(PIR1_ADDR) PIR1bits;
volatile __PIR2bits_t __at(PIR2_ADDR) PIR2bits;
volatile __PMCON1bits_t __at(PMCON1_ADDR) PMCON1bits;
volatile __PORTAbits_t __at(PORTA_ADDR) PORTAbits;
volatile __SLRCONAbits_t __at(SLRCONA_ADDR) SLRCONAbits;
volatile __STATUSbits_t __at(STATUS_ADDR) STATUSbits;
volatile __T1CONbits_t __at(T1CON_ADDR) T1CONbits;
volatile __T1GCONbits_t __at(T1GCON_ADDR) T1GCONbits;
volatile __T2CONbits_t __at(T2CON_ADDR) T2CONbits;
volatile __TRISAbits_t __at(TRISA_ADDR) TRISAbits;
volatile __WPUAbits_t __at(WPUA_ADDR) WPUAbits;

