CC = gcc
CFLAGS += -Wall -O2
CXXFLAGS += -fdollars-in-identifiers -ggdb

JAVAC = javac
JAVACFLAGS +=

OBJ = $(CSRC:.c=.o) $(JAVASRC:.java=.class) $(CCSRC:.cc=.o)

all: subdirs $(OBJ) $(BIN) $(LIB)

$(BIN): $(OBJ) $(EXTRA_LIBS)

$(LIB): $(OBJ)
	ar r $(LIB) $(OBJ)
	ranlib $(LIB)

%.class: %.java
	$(JAVAC) $<

subdirs:
ifdef SUBDIRS
	for i in $(SUBDIRS); do $(MAKE) -C $$i; done
endif

clean:
ifdef SUBDIRS
	for i in $(SUBDIRS); do $(MAKE) -C $$i clean; done
endif
	rm -f *.o *.class *~ *.a $(BIN) $(LIB)

